import type { Metadata } from 'next';
import { FAQSection } from '@/components/home/FAQSection';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

const BASE_URL = 'https://contentguard.saishshinde2030.workers.dev';
const PAGE_URL = `${BASE_URL}/faq`;
const TITLE = 'ContentGuard AI FAQ — Common Questions Answered';
const DESCRIPTION =
  'Answers to common questions about ContentGuard AI: how AI detection works, plagiarism checker accuracy, grammar tool, file formats, privacy, and whether it is free to use.';

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    'ContentGuard AI FAQ',
    'AI detector questions',
    'plagiarism checker help',
    'is AI content detector free',
    'how does plagiarism checker work',
    'AI detection accuracy',
    'ContentGuard support',
    'grammar checker FAQ',
    'is my content private',
    'writing tools FAQ',
  ],
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: PAGE_URL,
    siteName: 'ContentGuard AI',
    type: 'website',
    images: [
      {
        url: `${BASE_URL}/og-image.png`,
        width: 1200,
        height: 630,
        alt: TITLE,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [`${BASE_URL}/og-image.png`],
  },
};

export default function FAQPage() {
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How accurate is the AI content detector?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'ContentGuard AI uses advanced statistical analysis including perplexity, burstiness, and vocabulary richness metrics to identify AI-generated content. Our system provides reliable results with confidence scores and sentence-level heatmaps to help you make informed decisions.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is the plagiarism checker really free?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes! ContentGuard AI is completely free to use. No signup, no credit card, no hidden fees. We believe everyone should have access to professional-grade content quality tools.',
        },
      },
      {
        '@type': 'Question',
        name: 'What file formats are supported for upload?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'We support PDF, DOCX (Microsoft Word), and plain text (TXT) files with virtually no size limits. You can also paste text directly into the editor for instant analysis.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is my content stored or shared by ContentGuard AI?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Your privacy is our priority. ContentGuard AI does not store, share, or use your content for any purpose beyond the analysis you request. All processing happens in real-time and your text is not retained after analysis completes.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can ContentGuard AI detect ChatGPT, Claude, and Gemini text?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Our AI detector identifies text generated by ChatGPT (GPT-4, GPT-3.5), Claude (Anthropic), Gemini (Google), and other major AI language models using statistical signature analysis with model attribution scores.',
        },
      },
      {
        '@type': 'Question',
        name: 'How does the AI sentence heatmap work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Our AI heatmap analyzes each sentence individually and assigns a probability score. Sentences are color-coded: green for likely human-written, yellow/purple for mixed or uncertain content, and pink for likely AI-generated text.',
        },
      },
      {
        '@type': 'Question',
        name: 'Which citation styles does the citation generator support?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The ContentGuard AI citation generator supports APA 7th edition, MLA 9th edition, Harvard, and Chicago citation styles for websites, books, journal articles, and other source types.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can I use ContentGuard AI for academic papers and essays?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Absolutely. ContentGuard AI is designed for students, researchers, bloggers, and professionals. Our tools help ensure your content is original, well-written, properly cited, and at the right reading level for your audience.',
        },
      },
    ],
  };

  return (
    <div className="bg-bg-primary min-h-screen py-14 sm:py-20">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <div className="max-w-3xl mx-auto px-6">
        {/* Back Link */}
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-text-muted hover:text-text-primary transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to Home
          </Link>
        </div>

        <FAQSection />

        {/* Bottom support card */}
        <div className="mt-14 text-center">
          <div className="max-w-md mx-auto bg-bg-card border border-border-custom p-8 rounded-2xl shadow-md shadow-premium-glow">
            <h3 className="text-lg font-bold text-text-primary mb-2 font-syne">Have more questions?</h3>
            <p className="text-xs sm:text-sm text-text-muted mb-5 leading-relaxed">
              Our team is here to help with integrations, false positives, or API access.
            </p>
            <Link
              href="/contact"
              className="px-5 py-2.5 rounded-xl text-xs font-bold text-text-primary bg-gradient-to-r from-accent-purple to-accent-light-purple hover:shadow-[0_0_20px_rgba(124,92,252,0.35)] transition-all cursor-pointer inline-flex items-center gap-2"
            >
              Contact Support
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
