import type { Metadata } from 'next';
import { HeroSection } from '@/components/home/HeroSection';
import { FeaturesSection } from '@/components/home/FeaturesSection';
import { HowItWorks } from '@/components/home/HowItWorks';
import { SocialProof } from '@/components/home/SocialProof';

export const metadata: Metadata = {
  title: 'ContentGuard AI — Free Plagiarism Checker & AI Content Detector',
  description: 'Check plagiarism, detect AI-generated content, fix grammar, and analyze readability — 100% free, no signup required. Trusted by 10,000+ students and writers.',
  keywords: 'free plagiarism checker, AI content detector, check plagiarism online, AI detector free, grammar checker, readability analyzer, citation generator, word counter',
  alternates: {
    canonical: 'https://contentguard.saishshinde2030.workers.dev/',
  },
  verification: {
    google: 'z58V08TqQ3fW6VwI5ZJ-D3-78n8m1-u2Y0xV5E9v78I',
  },
  openGraph: {
    title: 'ContentGuard AI — Free Plagiarism Checker & AI Content Detector',
    description: 'Check plagiarism, detect AI-generated content, fix grammar, and analyze readability — 100% free, no signup required. Trusted by 10,000+ students and writers.',
    url: 'https://contentguard.saishshinde2030.workers.dev/',
    type: 'website',
    images: [
      {
        url: 'https://contentguard.saishshinde2030.workers.dev/og-image.png',
        width: 1200,
        height: 630,
        alt: 'ContentGuard AI — Free Plagiarism Checker & AI Content Detector',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ContentGuard AI — Free Plagiarism Checker & AI Content Detector',
    description: 'Check plagiarism, detect AI-generated content, fix grammar, and analyze readability — 100% free, no signup required. Trusted by 10,000+ students and writers.',
    images: ['https://contentguard.saishshinde2030.workers.dev/og-image.png'],
  },
};

export default function HomePage() {
  const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    'name': 'ContentGuard AI',
    'url': 'https://contentguard.saishshinde2030.workers.dev',
    'description': 'Free AI content detection, plagiarism checking, grammar analysis, and writing tools',
    'applicationCategory': 'UtilitiesApplication',
    'operatingSystem': 'Web',
    'offers': {
      '@type': 'Offer',
      'price': '0',
      'priceCurrency': 'USD',
    },
    'featureList': [
      'AI Content Detection',
      'Plagiarism Checker',
      'Grammar Checker',
      'Readability Analyzer',
      'Citation Generator',
      'Word Counter',
    ],
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    'mainEntity': [
      {
        '@type': 'Question',
        'name': 'Is ContentGuard AI free to use?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Yes, ContentGuard AI is 100% free to use with no signup required. All 6 tools are available at no cost.',
        },
      },
      {
        '@type': 'Question',
        'name': 'How does the plagiarism checker work?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'ContentGuard scans your text against billions of web pages and academic sources to detect copied content. Results show Unique%, Exact Match%, and Partial Match% with source links.',
        },
      },
      {
        '@type': 'Question',
        'name': 'Can it detect ChatGPT and AI-written content?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'Yes. ContentGuard AI detects text generated by ChatGPT, Claude, Gemini, and other AI models using advanced statistical markers like perplexity and burstiness.',
        },
      },
      {
        '@type': 'Question',
        'name': 'Do I need to create an account?',
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': 'No account or signup is required. Simply paste your text or upload a file and get instant results.',
        },
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <HeroSection />
      <SocialProof />
      <FeaturesSection />
      <HowItWorks />
    </>
  );
}
