import type { Metadata } from 'next';
import { HeroSection } from '@/components/home/HeroSection';
import { FeaturesSection } from '@/components/home/FeaturesSection';
import { HowItWorks } from '@/components/home/HowItWorks';
import { SocialProof } from '@/components/home/SocialProof';

const BASE_URL = 'https://contentguard.saishshinde2030.workers.dev';

export const metadata: Metadata = {
  title: 'Free AI Content Checker & Plagiarism Detector — ContentGuard AI',
  description:
    'Free AI content checker, plagiarism detector, grammar fixer & readability analyzer — no signup. Detect ChatGPT, Claude & Gemini text instantly. Trusted by 10,000+ writers.',
  keywords: [
    'free AI content checker',
    'plagiarism checker free',
    'AI detector free',
    'check plagiarism online free',
    'AI content detector',
    'detect ChatGPT text',
    'grammar checker online',
    'readability analyzer',
    'citation generator',
    'word counter free',
    'humanize AI text',
    'content originality checker',
  ],
  alternates: {
    canonical: BASE_URL + '/',
  },
  openGraph: {
    title: 'Free AI Content Checker & Plagiarism Detector — ContentGuard AI',
    description:
      'Free AI content checker, plagiarism detector, grammar fixer & readability analyzer — no signup. Detect ChatGPT, Claude & Gemini text instantly.',
    url: BASE_URL + '/',
    siteName: 'ContentGuard AI',
    type: 'website',
    images: [
      {
        url: BASE_URL + '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'ContentGuard AI — Free AI Content Checker & Plagiarism Detector',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free AI Content Checker & Plagiarism Detector — ContentGuard AI',
    description:
      'Free AI content checker, plagiarism detector, grammar fixer & readability analyzer — no signup. Detect ChatGPT, Claude & Gemini text instantly.',
    images: [BASE_URL + '/og-image.png'],
  },
  verification: {
    google: 'QV5UpQrtIwvvBBZtqvs4EjXGbMVRwKdi8yB4cCnD-qE',
  },
};

export default function HomePage() {
  const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'ContentGuard AI',
    url: BASE_URL,
    description:
      'Free AI content detection, plagiarism checking, grammar analysis, and writing tools. No signup required.',
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Web',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
    featureList: [
      'AI Content Detection',
      'Plagiarism Checker',
      'Grammar Checker',
      'Readability Analyzer',
      'Citation Generator',
      'Word Counter',
      'AI Text Humanizer',
    ],
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Is ContentGuard AI free to use?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, ContentGuard AI is 100% free to use with no signup required. All 7 tools are available at no cost.',
        },
      },
      {
        '@type': 'Question',
        name: 'How does the plagiarism checker work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'ContentGuard AI scans your text against billions of web pages and academic sources to detect copied content. Results show Unique%, Exact Match%, and Partial Match% with source links.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can it detect ChatGPT and AI-written content?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. ContentGuard AI detects text generated by ChatGPT, Claude, Gemini, and other AI models using advanced statistical markers like perplexity and burstiness.',
        },
      },
      {
        '@type': 'Question',
        name: 'Do I need to create an account?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'No account or signup is required. Simply paste your text or upload a file and get instant results.',
        },
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <HeroSection />
      <SocialProof />
      <FeaturesSection />
      <HowItWorks />
    </>
  );
}
