'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import {
  ArrowRight,
  Zap,
  ShieldCheck,
  SpellCheck,
  BookOpen,
  Users,
  Scan,
  Search,
} from 'lucide-react';

type TabType = 'ai' | 'plagiarism' | 'grammar';

export function HeroSection() {
  const [activeTab, setActiveTab] = useState<TabType>('ai');

  const tabContent = {
    ai: {
      text: (
        <>
          Artificial intelligence models are rapidly changing the way content is generated.{' '}
          <span className="bg-accent-pink/10 text-accent-pink border-b-2 border-accent-pink/30 px-1 py-0.5 rounded transition-all duration-300">
            This paragraph was entirely generated by a large language model to simulate AI patterns.
          </span>{' '}
          ContentGuard AI uses advanced statistical markers like perplexity and burstiness to detect these patterns in seconds.
        </>
      ),
      score: 78,
      scoreColor: 'text-accent-pink',
      strokeColor: '#ec4899',
      status: 'AI Detected',
      statusBg: 'bg-accent-pink/10 text-accent-pink border-accent-pink/20',
      metrics: [
        { label: 'AI Probability', value: '78%', icon: Zap, color: 'text-accent-pink' },
        { label: 'Readability', value: 'B-', icon: BookOpen, color: 'text-accent-light-purple' },
        { label: 'Confidence', value: '99.4%', icon: ShieldCheck, color: 'text-accent-green' },
      ],
    },
    plagiarism: {
      text: (
        <>
          Plagiarism checking is vital to protect your academic and professional integrity.{' '}
          <span className="bg-accent-light-purple/10 text-accent-light-purple border-b-2 border-accent-purple/30 px-1 py-0.5 rounded transition-all duration-300">
            Research shows that up to 14% of submitted materials contain duplicate paragraphs.
          </span>{' '}
          Our platform scans global databases to ensure your text is unique and properly cited.
        </>
      ),
      score: 86,
      scoreColor: 'text-accent-green',
      strokeColor: '#10b981',
      status: '86% Unique',
      statusBg: 'bg-accent-green/10 text-accent-green border-accent-green/20',
      metrics: [
        { label: 'Originality', value: '86%', icon: ShieldCheck, color: 'text-accent-green' },
        { label: 'Similarity Match', value: '14%', icon: Search, color: 'text-accent-pink' },
        { label: 'Matched Sources', value: '2 Sources', icon: BookOpen, color: 'text-accent-purple' },
      ],
    },
    grammar: {
      text: (
        <>
          Excellent writing requires precision, clarity, and correct styling. Scan your essays{' '}
          <span className="bg-accent-purple/10 text-accent-light-purple border-b-2 border-accent-purple/30 px-1 py-0.5 rounded transition-all duration-300">
            to instantly fix spelling typo and grammar mistakes
          </span>{' '}
          so that your final drafts present a highly professional impression.
        </>
      ),
      score: 96,
      scoreColor: 'text-accent-purple',
      strokeColor: '#7c5cfc',
      status: 'Excellent Tone',
      statusBg: 'bg-accent-purple/10 text-accent-light-purple border-accent-purple/20',
      metrics: [
        { label: 'Style Score', value: '96%', icon: SpellCheck, color: 'text-accent-purple' },
        { label: 'Corrections', value: '2 Issues', icon: Zap, color: 'text-accent-pink' },
        { label: 'Grade Level', value: 'Grade A', icon: BookOpen, color: 'text-accent-light-purple' },
      ],
    },
  };

  const current = tabContent[activeTab];

  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: 'spring' as const, stiffness: 100, damping: 15 } },
  };

  return (
    <section className="relative overflow-hidden pt-12 pb-20 sm:pb-28 lg:pb-36 bg-bg-primary border-b border-border-custom">
      {/* Background Grids */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_30%,rgba(124,92,252,0.06),transparent_50%)] pointer-events-none" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_80%,rgba(236,72,153,0.04),transparent_50%)] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
          
          {/* Left Column */}
          <motion.div 
            variants={containerVariants}
            initial="hidden"
            animate="show"
            className="lg:col-span-7 text-center lg:text-left flex flex-col items-center lg:items-start"
          >
            {/* Elegant Pill Badge */}
            <motion.div
              variants={itemVariants}
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-bg-card border border-border-custom text-xs font-semibold text-text-primary mb-6"
            >
              <span className="w-2.5 h-2.5 rounded-full bg-accent-green animate-pulse-dot" />
              100% Free · No Signup Required
            </motion.div>

            {/* Title */}
            <motion.h1
              variants={itemVariants}
              className="text-4xl sm:text-5xl lg:text-[3.25rem] xl:text-[3.75rem] font-syne font-extrabold tracking-tight leading-[1.1] mb-5 text-text-primary"
            >
              Free AI Content Detector &{' '}
              <span className="bg-gradient-to-r from-accent-purple via-accent-light-purple to-accent-pink bg-clip-text text-transparent">
                Plagiarism Checker
              </span>
            </motion.h1>

            {/* Description */}
            <motion.p
              variants={itemVariants}
              className="text-base sm:text-lg text-text-muted max-w-lg mb-8 leading-relaxed font-medium"
            >
              Verify authenticity in seconds. Detect ChatGPT, Claude, and Gemini text, check originality, correct grammar, and score readability.
            </motion.p>

            {/* CTA Buttons */}
            <motion.div
              variants={itemVariants}
              className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto"
            >
              <Link
                href="/ai-detector"
                className="w-full sm:w-auto px-8 py-3.5 rounded-xl font-bold text-sm text-text-primary bg-gradient-to-r from-accent-purple to-accent-light-purple hover:shadow-[0_0_25px_rgba(124,92,252,0.45)] transition-all duration-300 flex items-center justify-center gap-2 active:scale-95 group"
              >
                <Zap className="w-4 h-4" />
                Detect AI Content
                <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
              </Link>
              <Link
                href="/plagiarism-checker"
                className="w-full sm:w-auto px-8 py-3.5 rounded-xl font-bold text-sm text-text-primary border border-border-custom bg-bg-card hover:bg-bg-input hover:border-accent-purple/40 transition-all duration-300 flex items-center justify-center gap-2 active:scale-95"
              >
                <ShieldCheck className="w-4 h-4 text-text-muted" />
                Check Plagiarism
              </Link>
            </motion.div>

            {/* Fine Trust Indicators */}
            <motion.div
              variants={itemVariants}
              className="flex items-center gap-4 mt-8 text-xs text-text-muted font-medium"
            >
              <span className="flex items-center gap-1.5">
                <Users className="w-3.5 h-3.5 text-accent-purple" />
                10k+ daily users
              </span>
              <span className="w-1 h-1 rounded-full bg-border-custom" />
              <span>Real-time processing</span>
              <span className="w-1 h-1 rounded-full bg-border-custom" />
              <span>No document storage</span>
            </motion.div>
          </motion.div>

          {/* Right Column: High-Fidelity Mockup Dashboard */}
          <div className="lg:col-span-5 relative w-full flex justify-center lg:justify-end mt-4 lg:mt-0">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="w-full max-w-[420px] relative"
            >
              {/* Decorative floating card */}
              <motion.div
                animate={{ y: [0, -6, 0] }}
                transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute -top-6 -left-6 z-20 bg-bg-card border border-border-custom rounded-xl px-4 py-2.5 shadow-xl flex items-center gap-2 pointer-events-none shadow-premium-glow"
              >
                <span className="w-2 h-2 rounded-full bg-accent-green animate-pulse-dot" />
                <span className="text-[10px] font-bold text-text-primary uppercase tracking-wider">
                  Analysis Complete
                </span>
              </motion.div>

              <div className="relative bg-bg-card rounded-2xl border border-border-custom shadow-2xl overflow-hidden">
                {/* Window header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-border-custom bg-bg-primary/50">
                  <div className="flex items-center gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-border-custom" />
                    <div className="w-2.5 h-2.5 rounded-full bg-border-custom" />
                    <div className="w-2.5 h-2.5 rounded-full bg-border-custom" />
                  </div>
                  <div className="text-[10px] font-bold text-text-muted uppercase tracking-widest">
                    Contentguard Editor
                  </div>
                  <div className="w-12" />
                </div>

                {/* Real Tab bar selector */}
                <div className="flex border-b border-border-custom p-1.5 bg-bg-primary/20 gap-1">
                  {(['ai', 'plagiarism', 'grammar'] as const).map((tab) => {
                    const isActive = activeTab === tab;
                    const Icon = tab === 'ai' ? Scan : tab === 'plagiarism' ? Search : SpellCheck;
                    const labels = { ai: 'AI Detector', plagiarism: 'Plagiarism', grammar: 'Grammar' };
                    return (
                      <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                          isActive
                            ? 'bg-bg-input border border-border-custom text-accent-light-purple shadow-md'
                            : 'text-text-muted hover:text-text-primary'
                        }`}
                      >
                        <Icon className="w-3.5 h-3.5" />
                        {labels[tab]}
                      </button>
                    );
                  })}
                </div>

                {/* Dashboard body */}
                <div className="p-5 space-y-5">
                  {/* Mock Text area editor */}
                  <div className="bg-bg-input rounded-xl p-4 border border-border-custom min-h-[110px]">
                    <p className="text-xs sm:text-[13px] text-text-muted leading-relaxed font-medium">
                      {current.text}
                    </p>
                  </div>

                  {/* Metrics and score breakdown */}
                  <div className="grid grid-cols-12 gap-4 items-center">
                    {/* Circle Gauge */}
                    <div className="col-span-5 flex flex-col items-center justify-center border-r border-border-custom pr-4">
                      <div className="relative w-20 h-20 flex items-center justify-center">
                        <svg className="w-full h-full -rotate-90">
                          <circle cx="40" cy="40" r="34" fill="none" stroke="#2a2d3a" strokeWidth="4.5" />
                          <motion.circle
                            key={activeTab}
                            cx="40"
                            cy="40"
                            r="34"
                            fill="none"
                            stroke={current.strokeColor}
                            strokeWidth="4.5"
                            strokeDasharray={2 * Math.PI * 34}
                            initial={{ strokeDashoffset: 2 * Math.PI * 34 }}
                            animate={{ strokeDashoffset: (2 * Math.PI * 34) * (1 - current.score / 100) }}
                            transition={{ duration: 0.8, ease: 'easeOut' }}
                            strokeLinecap="round"
                          />
                        </svg>
                        <div className="absolute inset-0 flex flex-col items-center justify-center">
                          <span className={`text-lg font-bold font-syne ${current.scoreColor}`}>{current.score}%</span>
                        </div>
                      </div>
                      <div className={`mt-2 px-2.5 py-0.5 rounded-full border text-[9px] font-bold uppercase tracking-wider ${current.statusBg}`}>
                        {current.status}
                      </div>
                    </div>

                    {/* Side lists */}
                    <div className="col-span-7 space-y-2">
                      <AnimatePresence mode="wait">
                        <motion.div
                          key={activeTab}
                          initial={{ opacity: 0, x: 8 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: -8 }}
                          transition={{ duration: 0.2 }}
                          className="space-y-1.5"
                        >
                          {current.metrics.map((metric) => {
                            const Icon = metric.icon;
                            return (
                              <div
                                key={metric.label}
                                className="flex items-center justify-between bg-bg-input border border-border-custom rounded-lg px-3 py-1.5"
                              >
                                <div className="flex items-center gap-2">
                                  <Icon className="w-3.5 h-3.5 text-text-muted" />
                                  <span className="text-[10px] font-semibold text-text-muted">{metric.label}</span>
                                </div>
                                <span className={`text-[10px] font-bold ${metric.color}`}>{metric.value}</span>
                              </div>
                            );
                          })}
                        </motion.div>
                      </AnimatePresence>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

        </div>
      </div>
    </section>
  );
}
